const ACTION_TYPES = {
    GET_USER: 'GET_USER',
    GET_CHAT: 'GET_CHAT',
    GET_USER_ERROR: 'GET_USER_ERROR',
    ADD_NEW_MESSAGE: 'ADD_NEW_MESSAGE',
    GET_USER_CHATS: 'GET_USER_CHATS',
}

export default ACTION_TYPES