
# POST http://localhost:5000/api/chats/ HTTP/1.1
# Content-Type: application/json

# {
#     "chatName": "тріо"
# }

# PUT http://localhost:5000/api/chats/674f061eae85455912deb4ab HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzU4YzZmOThlNTZhYzZhNmQ0MmE4ZjUiLCJlbWFpbCI6ImNhdGUuZG9lQGdtYWlsLmNvbSIsImlhdCI6MTczMzk0MDY4MiwiZXhwIjoxNzMzOTQxMDQyfQ.abbszOzXL2_HgnWJWhP86MtWn3k0LkcP6ZpPvhJawKo

# GET http://localhost:5000/api/chats/ HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhZWVjNGE5NzNkM2UyY2UwZmFlNTQiLCJlbWFpbCI6InJheWFuMkBnbWFpbC5jcG0iLCJpYXQiOjE3MzUxNTk0NjYsImV4cCI6MTczNTE1OTgyNn0.CL6V_HUnLaKfLVNB8K836S9NVKPTW1WMS5hHS8jDpFs

# PUT http://localhost:5000/api/chats/674f0619ae85455912deb4a9 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhZWVjNGE5NzNkM2UyY2UwZmFlNTQiLCJlbWFpbCI6InJheWFuMkBnbWFpbC5jcG0iLCJpYXQiOjE3MzUxNTc2NDcsImV4cCI6MTczNTE1ODAwN30.NjBEgGtcmOYTxLdcdq-YxkNYZQzVitSUV_elyDn5YNw

# GET http://localhost:5000/api/chats/674f0619ae85455912deb4a9 HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhZWVjNGE5NzNkM2UyY2UwZmFlNTQiLCJlbWFpbCI6InJheWFuMkBnbWFpbC5jcG0iLCJpYXQiOjE3MzUxNTk0NjYsImV4cCI6MTczNTE1OTgyNn0.CL6V_HUnLaKfLVNB8K836S9NVKPTW1WMS5hHS8jDpFs


POST http://localhost:5000/api/chats/674f0619ae85455912deb4a9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzZhZWVjNGE5NzNkM2UyY2UwZmFlNTQiLCJlbWFpbCI6InJheWFuMkBnbWFpbC5jcG0iLCJpYXQiOjE3MzUxNjIyNzcsImV4cCI6MTczNTE2MjYzN30.u5NI7zWDCtb1oBOnJa69nmY8UXgdyOQeujJB2UUECO8

{
    "body": "HI]]"
}
